# Generated by Django 4.2.3 on 2023-07-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='conference_room',
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='conference_rooms.device'),
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='is_occupied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(blank=True, default='Name', max_length=100, unique=True),
        ),
    ]
